-- Phase 1 migration: profiles + captures (DATA-MODEL.md §captures/profiles + §trust spine).
--
-- STATUS: reviewed-by-construction, NOT yet applied/integration-tested against a live project.
-- Apply + verify once Supabase is connected (see docs/PHASE-1-SUPABASE.md). LocalOnlyAdapter
-- remains the app default until env vars are set.
--
-- Invariants enforced server-side (mirror src/lib/capture/apply.ts::applyOpToServer):
--   1. idempotent + in-order: ignore ops with client_seq <= the row's current seq
--   2. tombstone: status='discarded' is terminal — no op resurrects it
--   3. server clock: synced_at/server_seq are server-stamped; captured_at is display-only
-- Every user-owned table: user_id NOT NULL + FORCE RLS with a flat user_id = auth.uid() policy.

-- ───────────────────────── profiles (1:1 with auth.users) ─────────────────────────
create table if not exists public.profiles (
  id                   uuid primary key references auth.users (id) on delete cascade,
  display_name         text,
  timezone             text,                         -- IANA tz; anchors relative-date resolution
  working_hours        jsonb  not null default '{}'::jsonb,
  energy_pattern       jsonb  not null default '{}'::jsonb,
  onboarding_completed boolean not null default false,
  settings             jsonb  not null default '{}'::jsonb,
  ai_provider          text   not null default 'hosted_claude'
                         check (ai_provider in ('hosted_claude', 'byo_key', 'local', 'manual')),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.profiles force row level security;

create policy profiles_select on public.profiles for select using (id = auth.uid());
create policy profiles_insert on public.profiles for insert with check (id = auth.uid());
create policy profiles_update on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy profiles_delete on public.profiles for delete using (id = auth.uid());

-- Auto-create a profile row on signup.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, new.raw_user_meta_data ->> 'name')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ───────────────────────────────── captures (raw inbox) ─────────────────────────────────
create table if not exists public.captures (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  client_id    uuid not null,                          -- device-generated idempotency key
  client_seq   integer not null default 1,             -- per-row op sequence (out-of-order detection)
  raw_text     text not null default '',
  audio_key    text,                                   -- storage object key (NOT a URL); private bucket
  audio_status text not null default 'none'
                 check (audio_status in ('none', 'pending', 'uploading', 'stored', 'failed')),
  source       text not null default 'web'
                 check (source in ('web','ios_pwa','android_pwa','watch','shortcut','share_sheet','email','api')),
  captured_at  timestamptz,                            -- device clock — DISPLAY ONLY
  synced_at    timestamptz not null default now(),     -- server clock — authoritative
  skew_ms      integer,
  status       text not null default 'inbox'
                 check (status in ('inbox', 'clarifying', 'processed', 'discarded')),
  version      integer not null default 1,
  server_seq   bigint generated by default as identity, -- authoritative inbox ordering; stable across edits
  created_at   timestamptz not null default now(),
  unique (user_id, client_id)                          -- idempotency: one row per device capture
);

create index if not exists captures_user_status_idx     on public.captures (user_id, status);
create index if not exists captures_user_server_seq_idx  on public.captures (user_id, server_seq desc);

alter table public.captures enable row level security;
alter table public.captures force row level security;

create policy captures_select on public.captures for select using (user_id = auth.uid());
create policy captures_insert on public.captures for insert with check (user_id = auth.uid());
create policy captures_update on public.captures for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy captures_delete on public.captures for delete using (user_id = auth.uid());

-- ───────────── idempotent sync RPC — mirrors applyOpToServer (the trust spine) ─────────────
-- Applies an ordered array of ops for the CURRENT user and returns the resulting authoritative
-- rows. SECURITY INVOKER so RLS still scopes everything to auth.uid().
create or replace function public.sync_capture_ops(p_ops jsonb)
returns setof public.captures
language plpgsql
as $$
declare
  op       jsonb;
  uid      uuid := auth.uid();
  existing public.captures%rowtype;
  cid      uuid;
  seq      integer;
  kind     text;
  touched  uuid[] := '{}';
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  for op in select * from jsonb_array_elements(p_ops)
  loop
    cid  := (op ->> 'client_id')::uuid;
    seq  := (op ->> 'client_seq')::integer;
    kind := op ->> 'kind';

    select * into existing from public.captures
      where user_id = uid and client_id = cid for update;

    if found then
      -- (1) idempotent + in-order, and (2) tombstone is terminal
      if seq <= existing.client_seq or existing.status = 'discarded' then
        touched := touched || cid;
        continue;
      end if;

      update public.captures set
        client_seq = seq,
        version    = existing.version + 1,
        synced_at  = now(),
        raw_text   = case when kind = 'edit'       then coalesce(op ->> 'raw_text', raw_text) else raw_text end,
        status     = case when kind = 'delete'     then 'discarded'
                          when kind = 'set_status' then coalesce(op ->> 'status', status)
                          else status end
      where user_id = uid and client_id = cid;
    else
      -- only a create can materialize a new row; a non-create with no row is an orphan (skip)
      if kind = 'create' then
        insert into public.captures (user_id, client_id, client_seq, raw_text, source, captured_at, skew_ms, status, version)
        values (
          uid, cid, seq,
          coalesce(op ->> 'raw_text', ''),
          coalesce(op ->> 'source', 'web'),
          nullif(op ->> 'captured_at', '')::timestamptz,
          nullif(op ->> 'skew_ms', '')::integer,
          'inbox', 1
        );
      end if;
    end if;

    touched := touched || cid;
  end loop;

  return query
    select * from public.captures
    where user_id = uid and client_id = any(touched);
end;
$$;
